# Generated by Django 6.0.6 on 2026-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='task',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
