# Generated by Django 6.0.6 on 2026-06-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='tasks.task')),
            ],
            options={
                'ordering': ['-date', 'task__display_order'],
                'constraints': [models.UniqueConstraint(fields=('task', 'date'), name='unique_task_per_day')],
            },
        ),
    ]
