# Generated by Django 6.0.6 on 2026-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_dailytaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deactivated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
