# Generated by Django 6.0.6 on 2026-06-16 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
