# Generated by Django 6.0.6 on 2026-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateField(),
        ),
    ]
